# Generated by Django 3.2.5 on 2022-01-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='rating',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]),
        ),
    ]
